### PR TITLE
config: synchronize actual default value with the toml file

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Make the default values when missing a config file to be equivalent to the default TOML file.

Exposed a few settings in command line.

### What is changed and how it works?

Changed default values:

* checkpoint.enable = true
* post-restore.analyze = true
* csv.header = true
* csv.null = '\n'
* csv.backslash-escape = true

Exposed global / command line options:

* --no-schema=false
* --enable-checkpoint=true
* --analyze=true
* --checksum=true
* --check-requirements=true

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
    * inspect the config when running `bin/tidb-lightning --analyze=true`, `bin/tidb-lightning --analyze=false`, etc. 

Side effects

 - Breaking backward compatibility 
    * default value with no config value is changed.

Related changes

 - Need to update the documentation

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @GregoryIan

**Comment by kennytm** [comment]
Ping @GregoryIan

**Comment by kennytm** [comment]
PTAL @WangXiangUSTC @3pointer

**Comment by lance6716** [comment]
LGTM (from community)

**Comment by kennytm** [comment]
/run-all-tests

(Exposed --check-requirements to command line too.)

**Pull request merged**
