### PR TITLE
config: always skip the system databases

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Avoid importing the built-in databases (`mysql`, `information_schema`, `performance_schema` and `sys`).

### What is changed and how it works?

Add these 4 databases into the black list in `Adjust()`.

### Check List 

Tests 

 - Integration test

Side effects

 - Breaking backward compatibility
    * User has no way to explicitly restore the tables defined inside `mysql`.

Related changes

 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by lance6716** [comment]
LGTM

and I think user can restore those tables because

> If a database’s name matches both the do-dbs and ignore-dbs arrays, the database is included.

**Comment by kennytm** [comment]
PTAL @csuzhangxc

**Comment by ericsyh** [comment]
@kennytm Pls pick to the 3.0 branch

**Comment by kennytm** [comment]
It's already in the 3.0 branch.

**Pull request merged**
