### PR TITLE
checksum: fix pd service id is empty

### LINKED ISSUE #458: Lightning sets empty string as service ID for UpdateServiceGCSafePoint API
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Submitted a PR in PD's repo which added non-empty check for service ID in UpdateServiceGCSafePoint API: https://github.com/tikv/pd/pull/3146

2. What did you expect to see?

Everything works well

3. What did you see instead?

CI failed at lightning test because lightning sets empty string as the service ID when invoking UpdaetServiceGCSafePoint

```
[2020-11-09T07:30:13.887Z] tidb lightning encountered error:  restore table `alter_random`.`t` failed: rpc error: code = Unknown desc = service id of service safepoint cannot be empty.
```

And I read the code. It invokes the API here:

https://github.com/pingcap/tidb-lightning/blob/25a371155cf221d8a927882c4c5a23bcab8c649c/lightning/restore/checksum.go#L386-L387

and `m.serviceID` seems never set.

By the way, it also didn't check the return value of `UpdateServiceGCSafePoint`, which is useful for checking whether the actual GC safepoint has already exceeded the current set value. Please consider check it.

4. Versions of the cluster

    It occurs in CI and doesn't have detailed version info.

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        master
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        master
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        master
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        master
        ```

    - Other interesting information (system version, hardware config, etc):

        The issue may also exist in 4.0 branch.

5. Operation logs
   - No need
   
6. Configuration of the cluster and the task
   - No need

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

   - No need

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Fix empty gc safepoint service id 
close #458 

### What is changed and how it works?
Generate a random gc safe point service id for each lightning when building gc ttl manager

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

Related changes

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]
LGTM

**Comment by MyonKeminta** [comment]
Is service safepoint used in 4.0 branch?

**Comment by kennytm** [comment]
it is used only when the target cluster is 4.0+

**Comment by MyonKeminta** [comment]
If it's used in 4.0 branch, I think it need to be cherry-picked. Then if old version of lightning is used with new TiDB cluster with [this PR](https://github.com/tikv/pd/pull/3146) will still receive the error. I'm not sure if it's acceptable. If not, I think I need to remove the empty check...

**Comment by kennytm** [comment]
@MyonKeminta Lightning uses the branch for all of 3.0 to 5.0, so there's nothing to cherry-pick.

**Comment by MyonKeminta** [comment]
Got it. thanks.

**Pull request merged**
