### PR TITLE
backend: use peer address as grpc addr for tiflash store

### LINKED ISSUE #391: lightning fail to load data into a table with TiFlash replica
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    1. Deploy a TiDB cluster with one TiFlash node
    2. Create a table `ontime.ontime` with this schema: https://github.com/Percona-Lab/ontime-airline-performance/tree/master/mysql
    3. Add one TiFlash replica for that table `alter table ontime.ontime set tiflash replica 1`
    4. Use tidb-lightning to load data into `ontime.ontime`, using [TiDB Lightning Local-backend](https://docs.pingcap.com/zh/tidb/stable/tidb-lightning-backends#tidb-lightning-local-backend). The data to be loaded is 1000,000 lines.

2. What did you expect to see?

Data loaded successfully.

3. What did you see instead?

Data can not be loaded unless I remove the tiflash replica for that table.

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        >  ./tidb-lightning -V
        Release Version: v4.0.5
        Git Commit Hash: 0630432b0e3242da67bf0a0e0c3fb3679e4049d7
        Git Branch: master
        UTC Build Time: 2020-08-30 01:30:14
        Go Version: go version go1.13 linux/amd64
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        no
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        mysql ontime> select * from information_schema.cluster_info;
        +---------+------------------+-------------------+--------------------+------------------------------------------+---------------------------+------------------+
        | TYPE    | INSTANCE         | STATUS_ADDRESS    | VERSION            | GIT_HASH                                 | START_TIME                | UPTIME           |
        +---------+------------------+-------------------+--------------------+------------------------------------------+---------------------------+------------------+
        | tidb    | 172.16.5.85:8012 | 172.16.5.85:8512  | 5.7.25-TiDB-v4.0.4 | c61fc7247e9f6bc773761946d5b5294d3f2699a5 | 2020-09-07T20:41:24+08:00 | 13m0.951739693s  |
        | pd      | 172.16.5.85:6512 | 172.16.5.85:6512  | 4.0.4              | 096ab27038530fcf674a9f9d872609ec2656ee73 | 2020-09-07T20:41:12+08:00 | 13m12.951746351s |
        | tikv    | 172.16.5.85:7512 | 172.16.5.85:16512 | 4.0.4              | 28e3d44b00700137de4fa933066ab83e5f8306cf | 2020-09-07T20:41:19+08:00 | 13m5.951748112s  |
        | tiflash | 172.16.5.85:9512 | 172.16.5.85:17012 | v4.0.4             | bfa9128f59cf800e129152f06b12480ad78adafd | 2020-09-07T20:41:51+08:00 | 12m33.951749489s |
        +---------+------------------+-------------------+--------------------+------------------------------------------+---------------------------+------------------+
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        mysql ontime> select tidb_version();
       +-------------------------------------------------------------------+
       | tidb_version()                                                    |
       +-------------------------------------------------------------------+
       | Release Version: v4.0.4                                           |
       | Edition: Community                                                |
       | Git Commit Hash: c61fc7247e9f6bc773761946d5b5294d3f2699a5         |
       | Git Branch: heads/refs/tags/v4.0.4                                |
       | UTC Build Time: 2020-07-31 07:50:19                               |
       | GoVersion: go1.13                                                 |
       | Race Enabled: false                                               |
       | TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
       | Check Table Before Drop: false                                    |
       +-------------------------------------------------------------------+
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs

    - [lightning.log](https://github.com/pingcap/tidb-lightning/files/5183198/lightning.log)
    - Line 0 ~ 61 is a successful load since I have not created a tiflash replica yet.
    - Line 67 ~ the end is a fail load since I create another table and add a tiflash replica for it.

   
6. Configuration of the cluster and the task
   - The `tikv-importer.backend` is "local"
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
close #391 

### What is changed and how it works?
Use `store.GetPeerAddress` as the address to open gRPC connect and add a integration test for tiflash

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
please update `tests/README.md` to mention tiflash (or make the tiflash requirement optional).

rest LGTM

**Review by overvenus — APPROVED** [review]
LGTM

**Review by kennytm — APPROVED** [review]
LGTM

**Pull request merged**
