### PR TITLE
checkpoint: fix chunk checkpoint may reset offset and row id

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Fix chunk checkpoint `row_id` and `offset` maybe occasionally reset if chunk remain rows are empty.

Giving a sql source file: 
```
insert into a values (2);
```
And It's initial chunk checkpoint:
```
Chunk{Offset:0, EndOffset: 25, PrevRowIDMax: 8, RowIDMax:16}
```
After read the only first row, the checkpoint will be updated to:
```
Chunk{Offset:24, EndOffset: 25, PrevRowIDMax: 9, RowIDMax:16}
```
If lightning exit at this point and restart with checkpoint, then since this check offset < EndOffset , lightning will restore this chunk again, but there is no more row, so the checkpoint will be update as:
```
Chunk{Offset:0, EndOffset: 25, PrevRowIDMax: 0, RowIDMax:16}
```
By the current logic: https://github.com/pingcap/tidb-lightning/blob/6e39bb857e2d728c2eb676fbf4739d1f83b6a94d/lightning/restore/restore.go#L1717-L1770, which is obvious incorrent.

NOTE: this bug can cause some integration test fails occasionally. See: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/lightning_ghpr_test/detail/lightning_ghpr_test/1770/pipeline/

### What is changed and how it works?
Init the `row_id` and `offset` with the checkpoint previous values, so if there is no more rows, the fields won't be reset to default value.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]
LGTM

**Comment by kennytm** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/lightning_ghpr_test/detail/lightning_ghpr_test/1784/pipeline

```
[2020-09-11T07:42:10.638Z] Cannot contact test-go1130-memvolume-sk4tq: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on JNLP4-connect connection from 10.233.98.48/10.233.98.48:48978 failed. The channel is closing down or has closed down
```

**Pull request merged**
