### PR TITLE
tests: add test case for simple partitioned tables

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Verify pingcap/tidb#10796 works on Lightning.

### What is changed and how it works?

Added an integrated test case involving partitioned tables.

### Check List 

Tests 

 - Integration test

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @lance6716 @leoppro

**Comment by lance6716** [comment]
LGTM

**Pull request merged**
