### PR TITLE
metrics: copy the grafana board into this repo

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Copy the Grafana board from `tidb-ansible` into this repository.

### Check List 

Tests 

 - No code

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
/run-all-tests

PTAL @WangXiangUSTC (TOOL-1801)

**Comment by WangXiangUSTC** [comment]
how about also copy this file https://github.com/pingcap/tidb-ansible/blob/master/roles/prometheus/files/lightning.rules.yml

**Comment by kennytm** [comment]
Ok, didn't realize there's an alert rule 😓

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by kennytm** [comment]
PTAL @qiffang

**Comment by qiffang** [comment]
LGTM

**Pull request merged**
