### PR TITLE
test: make start tiflash optional in integration test

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Make TiFlash optional, so we can avoid trying to start tiflash with v3.0.0 tidb cluster
After this change, we need to add `TIFLASH=1` environment when run with v3.1 or upper cluster

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
LGTM but our Jenkins doesn't seem to set TIFLASH=1

**Comment by glorv** [comment]
> LGTM but our Jenkins doesn't seem to set TIFLASH=1

I have update our jenkins script as well as the pr in SRE repo https://github.com/pingcap/SRE/pull/347

**Comment by glorv** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by glorv** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by glorv** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by glorv** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by glorv** [comment]
/run-all-tests tidb=release-3.1 tikv=release-3.1 pd=release-3.1

**Review by 3pointer — APPROVED** [review]
LGTM

**Pull request merged**
