### PR TITLE
Support store version format generated by `git describe --tags`

### PR DESCRIPTION
**Pull request by solotzg**
Signed-off-by: Tong Zhigao <tongzhigao@pingcap.com>

### What problem does this PR solve? 

- Support store version format generated by `git describe --tags`, like `v4.1.0-alpha-9-ga27a7dd`.

### Check List 

Tests 

 - Manual

### CODE REVIEW

**Comment by solotzg** [comment]
I've added test case in `lightning/restore/checkreq_test.go`, PTAL. @kennytm

**Comment by kennytm** [comment]
/run-integration-test tidb=release-3.1 pd=release-3.1 tikv=release-3.1

**Comment by kennytm** [comment]
/run-all-tests tidb=release-3.1 pd=release-3.1 tikv=release-3.1

**Pull request merged**
