### PR TITLE
[WIP] Skip the entire KV encoder

### PR DESCRIPTION
**Pull request by kennytm**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by kennytm** [comment]
After this PR, the time to read + encode + deliver the entire 256 MiB file of the 6.5 TiB schema is reduced from ~3.75 minutes to ~2.5 minutes.

But now we need to clear the review of all other PRs first 🤷...

**Comment by lonng** [comment]
We need to take account in that values contain an expressions, e.g. `insert into t1 (c1, c2, c3) values (100, default(c2), year('2018-02-03'))`.

I think we can reuse `pingcap/parser` to parse `content` to `ast.ExprNode` and other API(https://github.com/pingcap/tidb/blob/0b371ea4fa95a829aa83376d9882dae10bee15d2/expression/expression.go#L39) to get the `types.Datum`.

**Pull request closed without merging**
