### PR TITLE
local: fix infinity loop in retry get region

### LINKED ISSUE #416: fix the `Reader.Read` bug in `parquet-go`
https://github.com/pingcap/br/pull/548 will fix the wrong implement of `Reader.Read` for s3 storage Reader, but  there is a [bug](https://github.com/xitongsys/parquet-go/pull/326) in `parquet-go` that may cause reading parquet file failed. So we should update `br` and `parquet-go` together after these two pr are merged.

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
- fix retry GetRegion infinity loop in retry ingest
- update br and parquet-go to fix #416

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### Release Note
- fix a bug that cause local backend retry get region in infinity loop

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
LGTM

**Comment by YuJuncen** [comment]
LGTM

**Comment by YuJuncen** [comment]
LGTM

**Review by overvenus — APPROVED** [review]
Please add release notes in the PR description.

**Pull request merged**
