### PR TITLE
restore: fix tablename case issue

### PR DESCRIPTION
**Pull request by AndrewDi**
### What problem does this PR solve? 
tablename and schema could be upper case,we should not convert it to lower case

### What is changed and how it works?
remove toLower func

### Check List 

Tests 

 - Unit test

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by kennytm** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by kennytm** [comment]
I don't think this fix is relevant to the issue...

**Comment by glorv** [comment]
since we have supported `mydumper.case-sensitive`, shall we close this now?

**Comment by kennytm** [comment]
yes let's close.

thanks for the contribution @AndrewDi 🙂.

**Pull request closed without merging**
