### PR TITLE
cmd: do not exit(1) if failed to sync log

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Even if the log file failed to sync (usually caused by log file = /dev/stdout), it shouldn't cause the program to exit with failure.

### What is changed and how it works?

Remove the condition that sync log fail causing exit(1).

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
    * Run the program

Side effects

Related changes

 - Need to cherry-pick to the release branch (2.1)

### CODE REVIEW

**Comment by kennytm** [comment]
/run-all-tests

PTAL @lance6716 @WangXiangUSTC

**Comment by lance6716** [comment]
LGTM

**Comment by kennytm** [comment]
Thanks. But I'd argue that even if the error is _not_ an `*os.PathError`, we should still not cause the program to `exit(1)`, because the error code is used to determine whether the data is successfully imported into the TiDB cluster.  The log being incomplete is irrelevant if the import succeed.

**Comment by gregwebs** [comment]
I agree. But I still want to know about any issues where the system is not behaving properly. So I would at least want to see the error logged (if it is not a PathError about stdout/stderr).

**Comment by lance6716** [comment]
exclude minimal error 😄

**Comment by kennytm** [comment]
@gregwebs The sync error is already written to stderr in lines 64–67.

**Comment by gregwebs** [comment]
okay, that's good then. It is still going to produce spurious stderr though, so its still best to ignore it if we know specifically what the error is.

**Comment by gregwebs** [comment]
It's confusing to still see the sync error in the log

**Pull request merged**
