### PR TITLE
restore: fix the potential null pointer exception when logging progress

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

If no files are completely imported within the first 5 minutes, we get `finished == 0` and the logger will try to log a nil field and crashes.

### What is changed and how it works?

Added a branch to ensure all fields are initialized.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
    * Run the program with `log-progress` set to `1s`.

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by kennytm** [comment]
PTAL @lonng @GregoryIan

**Comment by suzaku** [comment]
LGTM

**Pull request merged**
