### PR TITLE
make: hide go.mod to resolve cyclic dependency with tidb

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
Solve the cyclic dependency issue with tidb repo.

### What is changed and how it works?
rename `go.mod` and revert it temporary in Makefile

### Check List 

Tests 

 - No code

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
please follow 

https://github.com/pingcap/br/commit/7d62d5ff67e38edb82d5224d5904462bfce5dcf9#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

and

https://github.com/pingcap/br/commit/c6edb283f75fc5d5c95aebcd9d8ddb6d045c42df#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

too.

rest LGTM.

**Comment by lance6716** [comment]
added, ping @kennytm @overvenus

**Review by kennytm — COMMENTED** [review]
lgtm

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
