### PR TITLE
restore: support split csv source file with header

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Support split large csv files with header

### What is changed and how it works?
publish header to each chunk when split csv files, so when restore chunk, we can reader column names from chunk info.

### Benchmark result:
Bench with single source datafile size in 1.1GB:

use master commit, restore cost: 8.6s total cost: 30.5s
```
[2020/08/03 13:34:59.210 +08:00] [INFO] [restore.go:843] ["restore engine completed"] [table=`noheader`.`customer`] [engineNumber=0] [takeTime=8.573293547s] []
[2020/08/03 13:35:10.670 +08:00] [INFO] [restore.go:1109] ["local checksum"] [table=`noheader`.`customer`] [checksum="{cksum=15306146695610273290,size=1479995146,kvs=5760000}"]
[2020/08/03 13:35:21.104 +08:00] [INFO] [restore.go:605] ["restore table completed"] [table=`noheader`.`customer`] [takeTime=30.47492601s] []
```

use this comit: restore cost: 38s total cost: 59s
```
[2020/08/03 13:47:21.646 +08:00] [INFO] [restore.go:843] ["restore engine completed"] [table=`test`.`customer`] [engineNumber=0] [takeTime=38.462242082s] []
[2020/08/03 13:47:35.041 +08:00] [INFO] [restore.go:1446] ["checksum pass"] [table=`test`.`customer`] [local="{cksum=12990959430449404358,size=1479995146,kvs=5760000}"]
[2020/08/03 13:47:42.276 +08:00] [INFO] [restore.go:605] ["restore table completed"] [table=`test`.`customer`] [takeTime=59.096241639s] []
```

NOTE: this pr is base on the commits in #362 .

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by kennytm** [comment]
(WIP depends on #362)

**Comment by glorv** [comment]
@kennytm @3pointer @XuHuaiyu  PTAL

**Review by 3pointer — APPROVED** [review]
LGTM

**Pull request merged**
