### PR TITLE
test: fix integration test for 3.x version

### LINKED ISSUE #388: Support clustered index
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently when clustered index is enabled, the `_tidb_rowid` column is missing (?) and causes test failure. 

**Describe the feature you'd like:**

Support clustered index.

**Describe alternatives you've considered:**

No alternatives.

**Teachability, Documentation, Adoption, Optimization:**

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
- Skip run test `file-routing` with local backend when verion < v4.0.0
- Run integration test `common_handle` for all 3 backend
- fix a occasional test failure for `checkpoint_error_destroy` do to remain checkpoint file by other test.  see: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/lightning_ghpr_test/detail/lightning_ghpr_test/1720/pipeline/

close #388

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Comment by glorv** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by glorv** [comment]
/run-all-tests tidb=release-3.1 tikv=release-3.1 pd=release-3.1

**Review by kennytm — COMMENTED** [review]
Lgtm

**Review by 3pointer — APPROVED** [review]
LGTM

**Pull request merged**
