### PR TITLE
Cherry-pick 2.1: Fix interpretation of integers in a BIT column (#161)

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Cherry-picks #161 to 2.1 for 2.1.9 release. 

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

Related changes

 - Need to be included in the release note

### CODE REVIEW

**Comment by kennytm** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by kennytm** [comment]
PTAL @GregoryIan @lonng

**Comment by GregoryIan** [comment]
do we need [code](https://github.com/pingcap/tidb-lightning/pull/161/files#diff-24429677b84d3a72eee0e75a50ccc160R19)?

**Comment by lonng** [comment]
LGTM

**Comment by kennytm** [comment]
@GregoryIan No, that specific line was added to fix breakage introduced in #157, but was specifically *not* backported to 2.x.

**Comment by GregoryIan** [comment]
LGTM

**Pull request merged**
