### PR TITLE
go.mod: upgrade dependencies, esp TiDB -> v3.0.0-beta.1

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Keep the direct dependencies up-to-date.

This PR indicates the diversion of master from release-2.1. Merge this after the feature set of 2.1.8 is decided.

### What is changed and how it works?

Upgrade TiDB dependency from v2.1.5-13-gea9970968 to v3.0.0-beta.1.

### Check List 

Tests 

 - Unit test

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @csuzhangxc

**Comment by GregoryIan** [comment]
for log?  LGTM

**Pull request merged**
