### PR TITLE
mock: update rpc endpoint

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
Fit interface with https://github.com/tikv/importer/pull/19

### What is changed and how it works?
Use `mockgen` to generate latest gRPC mock files.

### Check List 

Tests 

 - Unit test

Side effects

Related changes

### CODE REVIEW

**Comment by lance6716** [comment]
run-all-tests

**Comment by lance6716** [comment]
PTAL @kennytm @leoppro

**Comment by kennytm** [comment]
PTAL @leoppro

**Comment by leoppro** [comment]
LGTM

**Pull request merged**
