### PR TITLE
mydump: add a warning log on large file with CSV header

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Auto-splitting requires (1) `strict-format = true` and (2) `csv.header = false`. Since `csv.header = true` by default, it would be confusing that setting `strict-format = true` alone has no effect.

### What is changed and how it works?

Add a warning if a large CSV file cannot be split only because of `csv.header`.

### Check List 

Tests 

 - No code

Side effects

Related changes

### CODE REVIEW

**Comment by glorv** [comment]
I think we can still split large csv files even if they contains header line?

**Comment by kennytm** [comment]
only if we read the header before splitting. this changes the scanning logic considerably.

**Comment by glorv** [comment]
LGTM. BTW, I think it's strage for user that we can't split large csv because of head line? As a use, I will think, why not just skip the first line and split the rest

**Comment by kennytm** [comment]
@glorv the problem is we can't just skip the first line, since the CSV column order and `CREATE TABLE` column order are not necessarily equivalent.

**Comment by overvenus** [comment]
LGTM

**Comment by kennytm** [comment]
should we close this in favor of #363, or merge this first?

**Comment by overvenus** [comment]
I prefer to close this if we can merge #363 before the next release (about 2020/08/21).

**Comment by kennytm** [comment]
#363 has been merged.

**Pull request closed without merging**
