### PR TITLE
lightning: ensure the web interface still works outside server mode

### LINKED ISSUE #231: Progress webpage fails to load in non-server mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Deploying tidb-lightning using k8s via https://github.com/pingcap/tidb-operator/pull/817
```
git clone https://github.com/tennix/tidb-operator -b tidb-lightning
cd tidb-operator
helm install charts/tidb-cluster -n <cluster-release-name> --namespace <namepsace> --set importer.create=true
helm install charts/tidb-lightning -n <lightning-release-name> --namespace <namespace> --set dataSource.local.nodeName=<node-name>,dataSource.local.hostPath=<host-path>,targetTidbCluster.name=<cluster-release-name>
```
Then view the lightning service

2. What did you expect to see?

The web page shows the task progress correctly.

3. What did you see instead?

The page shows and disappears immediately.

4. Versions of the cluster

The version of the cluster is v3.0.1. The corresponding images are pulled from DockerHub.

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Fix #231. 

### What is changed and how it works?

Implement `GET /tasks`, `GET /tasks/$id` and `DELETE /tasks/$id` even when the config list is nil.

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
    * run Lightning without server mode and access the web interface.

Side effects

Related changes

 - Need to be included in the release note

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @july2993 @amyangfei

**Comment by lance6716** [comment]
> Implement GET /tasks, GET /tasks/$id and DELETE /tasks/$id even when the config list is nil.

"when the config list is nil" happens only in non-server mode? That's not as apparent as "non-server mode"

**Comment by kennytm** [comment]
@lance6716 yeah this is explained in 

https://github.com/pingcap/tidb-lightning/blob/f9f6d8bf6ff5b558a2be5b4c574d5515f000711d/lightning/lightning.go#L258-L263

In non-server mode, each execution only run one task, so there is no need to initialize the config list. This was used to deduce the error message.

**Pull request merged**
