### PR TITLE
Cherry-pick 2.1: Replace gofail with new failpoint implementation (#165)

### PR DESCRIPTION
**Pull request by lonng**
Signed-off-by: Lonng <chris@lonng.org>

### What problem does this PR solve? 

Cherry-pick #165 to 2.1 for 2.1.9 release.

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

Related changes

### CODE REVIEW

**Comment by lonng** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by lonng** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by kennytm** [comment]
Test failure blocked by #164.

**Comment by lonng** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by lonng** [comment]
@kennytm @GregoryIan PTAL

**Comment by GregoryIan** [comment]
LGTM

**Pull request merged**
