### PR TITLE
go.mod: update dependencies (tidb -> 3.0.4)

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Just update all dependencies, in particular update TiDB to v3.0.4.

### What is changed and how it works?

Modify `go.mod` and `tools/go.mod`.

### Check List 

Tests 

 - Unit test

Side effects

Related changes

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by kennytm** [comment]
Ping @3pointer / PTAL @GregoryIan

**Comment by GregoryIan** [comment]
LGTM

**Pull request merged**
