### PR TITLE
lightning: check checkpoint schema conflict 

### LINKED ISSUE #353: ignore the checkpoint schema during restoring
I incorrectly backed up the original lighting checkpoint schema in the full backup, so during the restoring, it overwrote the currently working checkpoint schema, caused the restore failed. maybe we should ignore it in this case.

```
Error: restore table `tidb_lightning_checkpoint`.`engine_v5` failed: checksum mismatched remote vs local => (checksum: 8787980310280661993 vs 13761183867493318720) (total_kvs: 690 vs 32) (total_bytes:47888 vs 2132)
tidb lightning encountered error:  restore table `tidb_lightning_checkpoint`.`engine_v5` failed: checksum mismatched remote vs local => (checksum: 8787980310280661993 vs 13761183867493318720) (total_kvs: 690 vs 32) (total_bytes:47888 vs 2132)
```

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
When checkpoint is enable and use `mysql` driver, if there are some data file which name is same as checkpoint schema, return an error and exit before start restore. 
close #353 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
/run-all-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0 importer=release-4.0

**Comment by 3pointer** [comment]
Test Failed. Need TiKV merge this PR https://github.com/tikv/tikv/pull/8298 first

**Pull request merged**
