### PR TITLE
restore: fix gc life time not recovered after table restore (#218)

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Cherry-pick #218 to release-2.1.

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

Related changes

### CODE REVIEW

**Comment by amyangfei** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by amyangfei** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by amyangfei** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Comment by leoppro** [comment]
LGTM

**Pull request merged**
