### PR TITLE
metrics/grafana: add uid

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
fix  https://github.com/pingcap/tiup/issues/1166

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
Lightning has been moved into BR, so you should change https://github.com/pingcap/br/blob/master/metrics/grafana/lightning.json instead.

**Comment by glorv** [comment]
Do we need to accept this PR for v3.x version? @kennytm

**Comment by july2993** [comment]
> Hmm regardless of the maintenance of 3.x this PR should still be filed to the BR repo.

I think we should update the readme and archive this repository

**Comment by glorv** [comment]
> Hmm regardless of the maintenance of 3.x this PR should still be filed to the BR repo.

yes, I mean we should also keep this PR.

**Comment by lucklove** [comment]
> Lightning has been moved into BR, so you should change https://github.com/pingcap/br/blob/master/metrics/grafana/lightning.json instead.

It seems that TiUP uses lightning.json in this repo all the time: https://github.com/PingCAP-QE/ci/blob/jenkins-pipelines/jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy#L95

**Comment by 9547** [comment]
It doesn't matter, I'll file a PR in BR's repo later today

**Pull request closed without merging**
