### PR TITLE
main: sync log before exit + update failpoint dep

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

We need to sync the logger before exit. https://godoc.org/go.uber.org/zap#Logger.Sync

### What is changed and how it works?

Added a call to `Sync()`, modeled after TiDB https://github.com/pingcap/tidb/blob/b864fac504f9f059a39a7d477e923440f6d88a55/tidb-server/main.go#L176-L182.

Also, updated failpoint deps, see pingcap/dm#122.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
    * `make` works

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @july2993 @lonng

**Comment by csuzhangxc** [comment]
`Sync()` will also flush child logger's buffered entries, right?

**Comment by kennytm** [comment]
@csuzhangxc Yes. 

Calling [`With`](https://github.com/uber-go/zap/blob/badef736563f8135e0add3232b06f58656da03c8/zapcore/core.go#L72-L76) on an I/O Core would create a "clone" which [share the same WriteSyncer](https://github.com/uber-go/zap/blob/badef736563f8135e0add3232b06f58656da03c8/zapcore/core.go#L111). This means `parent.Sync()` and `child.Sync()` are both equivalent.

**Pull request merged**
